### ISSUE TITLE
Mattermost ins Deployment aufnehmen

### ISSUE THREAD

**Issue by piepmatz** [Strassengezwitscher/deployment#2]
Mattermost wird noch überhaupt nicht beachtet beim Deployment, abgesehen vom TLS-Zertifikat, das geholt wird.
Es wäre schön, wenn die Installation usw. ebenfalls automatisiert werden könnte.

**Comment by Bensk1** [comment]
Ich weiß nicht, ob Mattermost so eng zum Projekt gehört. Vielleicht lassen wir das erstmal raus?

**Comment by piepmatz** [comment]
Stimmt schon, hat mit dem Deployment des Codes nichts zu tun.
Das hängt letztlich davon ab, welche Rolle wir dem Deployment-Repo geben:
- Deployment des Codes oder
- möglichst vollständige Einrichtung des Servers, auf dem unter anderem der Code deployed wird.

Das Deployment von Mattermost fällt unter die zweite Option. Zu dieser würde dann aber noch einiges mehr gehören. Das sprengt dann tatsächlich etwas den Rahmen und das brauchen wir auch gar nicht.
Danke für deinen Einwand.
